# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a89aa52e8a8fd599b161cb776dd8124599cd39822173b93d1d1bc54ee028b04a69781b65e559e52f104ccb0ddd99c3fb508e272442e947cead0f1a3765cc233
  devise_secret_key: 0d30a44501e0189d30244b096a8f291c86fe65fcc81fc06ee9873637c64af623a80f3890145756738b8a98cf3bc5affe34614fb0c7b9905c499484a0950ddc59
  flickr_api_key: secret
  flickr_api_secret: secret
  twitter_consumer_key: secret
  twitter_consumer_secret: secret

test:
  secret_key_base: b875e6b656cbd399e7ce14d16769a63058f029179fa9661bf44f3c4468ff88b0ed39fbfefaa0cfbaba4c13a387d134e572da950687ffb7a4b331cdac798a6df8
  devise_secret_key: b70842b0ff80ad0113a93a7a7a3f8379407531ead92a3a2226a38a53f43bd0d17f622aa64cfd4f0f0c499cadbb44d02d09bcd921b0a2774225158def1641edfd
  flickr_api_key: secret
  flickr_api_secret: secret
  twitter_consumer_key: secret
  twitter_consumer_secret: secret

# Do not keep production secrets in the repository,
# instead read values from the environment.
# Use rake heroku:secrets RAILS_ENV=production to push config vars to heroku
# See "Config Variables" on https://dashboard.heroku.com/apps/<app_name>/settings
production:
  secret_key_base: secret
  devise_secret_key: secret
  flickr_api_key: secret
  flickr_api_secret: secret
  twitter_consumer_key: secret
  twitter_consumer_secret: secret
