require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MeetupGroupsController do

  # This should return the minimal set of attributes required to create a valid
  # MeetupGroup. As you add validations to MeetupGroup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "owner_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MeetupGroupsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all meetup_groups as @meetup_groups" do
      meetup_group = MeetupGroup.create! valid_attributes
      get :index, {}, valid_session
      assigns(:meetup_groups).should eq([meetup_group])
    end
  end

  describe "GET show" do
    it "assigns the requested meetup_group as @meetup_group" do
      meetup_group = MeetupGroup.create! valid_attributes
      get :show, {:id => meetup_group.to_param}, valid_session
      assigns(:meetup_group).should eq(meetup_group)
    end
  end

  describe "GET new" do
    it "assigns a new meetup_group as @meetup_group" do
      get :new, {}, valid_session
      assigns(:meetup_group).should be_a_new(MeetupGroup)
    end
  end

  describe "GET edit" do
    it "assigns the requested meetup_group as @meetup_group" do
      meetup_group = MeetupGroup.create! valid_attributes
      get :edit, {:id => meetup_group.to_param}, valid_session
      assigns(:meetup_group).should eq(meetup_group)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MeetupGroup" do
        expect {
          post :create, {:meetup_group => valid_attributes}, valid_session
        }.to change(MeetupGroup, :count).by(1)
      end

      it "assigns a newly created meetup_group as @meetup_group" do
        post :create, {:meetup_group => valid_attributes}, valid_session
        assigns(:meetup_group).should be_a(MeetupGroup)
        assigns(:meetup_group).should be_persisted
      end

      it "redirects to the created meetup_group" do
        post :create, {:meetup_group => valid_attributes}, valid_session
        response.should redirect_to(MeetupGroup.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved meetup_group as @meetup_group" do
        # Trigger the behavior that occurs when invalid params are submitted
        MeetupGroup.any_instance.stub(:save).and_return(false)
        post :create, {:meetup_group => { "owner_id" => "invalid value" }}, valid_session
        assigns(:meetup_group).should be_a_new(MeetupGroup)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MeetupGroup.any_instance.stub(:save).and_return(false)
        post :create, {:meetup_group => { "owner_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested meetup_group" do
        meetup_group = MeetupGroup.create! valid_attributes
        # Assuming there are no other meetup_groups in the database, this
        # specifies that the MeetupGroup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MeetupGroup.any_instance.should_receive(:update).with({ "owner_id" => "1" })
        put :update, {:id => meetup_group.to_param, :meetup_group => { "owner_id" => "1" }}, valid_session
      end

      it "assigns the requested meetup_group as @meetup_group" do
        meetup_group = MeetupGroup.create! valid_attributes
        put :update, {:id => meetup_group.to_param, :meetup_group => valid_attributes}, valid_session
        assigns(:meetup_group).should eq(meetup_group)
      end

      it "redirects to the meetup_group" do
        meetup_group = MeetupGroup.create! valid_attributes
        put :update, {:id => meetup_group.to_param, :meetup_group => valid_attributes}, valid_session
        response.should redirect_to(meetup_group)
      end
    end

    describe "with invalid params" do
      it "assigns the meetup_group as @meetup_group" do
        meetup_group = MeetupGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MeetupGroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => meetup_group.to_param, :meetup_group => { "owner_id" => "invalid value" }}, valid_session
        assigns(:meetup_group).should eq(meetup_group)
      end

      it "re-renders the 'edit' template" do
        meetup_group = MeetupGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MeetupGroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => meetup_group.to_param, :meetup_group => { "owner_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested meetup_group" do
      meetup_group = MeetupGroup.create! valid_attributes
      expect {
        delete :destroy, {:id => meetup_group.to_param}, valid_session
      }.to change(MeetupGroup, :count).by(-1)
    end

    it "redirects to the meetup_groups list" do
      meetup_group = MeetupGroup.create! valid_attributes
      delete :destroy, {:id => meetup_group.to_param}, valid_session
      response.should redirect_to(meetup_groups_url)
    end
  end

end
